# Generated by Django 5.2.5 on 2026-09-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Classified message text')),
                ('predicted_label', models.CharField(choices=[('HAM', 'Ham (Legitimate)'), ('SPAM', 'Spam (Unsolicited)')], max_length=10)),
                ('spam_probability', models.FloatField(help_text='Probability of spam [0.0 - 1.0]')),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('CRITICAL', 'Critical Spam')], max_length=20)),
                ('top_contributing_tokens', models.JSONField(blank=True, default=list)),
                ('inference_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
